
name: HOTFIX

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Enter valid tag name'
        type: string
        required: true

jobs:
  hot-fix:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Generate github app token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.ORG_POLICY_GITHUB_APP_ID }}
          private_key: ${{ secrets.ORG_POLICY_GITHUB_APP_PRIVATE_KEY }}

      - name: Use temporary github token as Env variable
        env:
          GITHUB_APP_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${GITHUB_APP_TOKEN}"
          echo "GITHUB_APP_TOKEN=$GITHUB_APP_TOKEN" >> $GITHUB_ENV
          echo "GITHUB_PR_TOKEN=${{ secrets.PULL_REQUEST_SECRET }}" >> $GITHUB_ENV
        shell: bash

      - name: Clone App repo
        uses: actions/checkout@v3.3.0
        with:
          token: ${{ env.GITHUB_APP_TOKEN }}
          ref: ${{ inputs.tag }}
          


      - name: Clone Managed CI
        uses: actions/checkout@v3.3.0
        with:
          repository: glcp/managed-ci-workflow
          token: ${{ env.GITHUB_APP_TOKEN }}
          path: managed-ci
          ref: main
