name: testing JFORG

on:
  push:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set JFrog Credentials
        id: jfrog-creds
        uses: githubactions-omkar/repo-2@main
        with:
          JFROG_URL: ${{ secrets.JFROG_URL }}

      - name: Print JFrog Credentials
        run: |
          echo "JFROG_USERNAME: $JFROG_USERNAME"
          echo "JFROG_PASSWORD: $JFROG_PASSWORD"
