name: testing JFORG

on:
  push:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Reusable Workflow
        id: call-reusable
        uses: githubactions-omkar/repo-2@main
        with:
          JFROG_URL: ${{ secrets.JFROG_URL }}
        secrets:
          ARUBA_JFROG_USERNAME: ${{ secrets.ARUBA_JFROG_USERNAME }}
          ARUBA_JFROG_PASSWORD: ${{ secrets.ARUBA_JFROG_PASSWORD }}
          CSS_JFROG_USERNAME: ${{ secrets.CSS_JFROG_USERNAME }}
          CSS_JFROG_PASSWORD: ${{ secrets.CSS_JFROG_PASSWORD }}
          DEFAULT_JFROG_USERNAME: ${{ secrets.DEFAULT_JFROG_USERNAME }}
          DEFAULT_JFROG_PASSWORD: ${{ secrets.DEFAULT_JFROG_PASSWORD }}

      - name: Print JFrog Credentials
        run: |
          echo "JFROG_USERNAME: ${{ steps.call-reusable.outputs.JFROG_USERNAME }}"
          echo "JFROG_PASSWORD: ${{ steps.call-reusable.outputs.JFROG_PASSWORD }}"


          
