name: testing JFORG

on:
  push:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    outputs:
      JFROG_USERNAME: ${{ steps.printvars.outputs.JFROG_USERNAME }}
      JFROG_PASSWORD: ${{ steps.printvars.outputs.JFROG_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Call Reusable Workflow
        id: call-reusable
        uses: githubactions-omkar/repo-2@main
        with:
          JFROG_URL: ${{ secrets.JFROG_URL }}
          ARUBA_JFROG_USERNAME: ${{ secrets.ARUBA_JFROG_USERNAME }}
          ARUBA_JFROG_PASSWORD: ${{ secrets.ARUBA_JFROG_PASSWORD }}
          CSS_JFROG_USERNAME: ${{ secrets.CSS_JFROG_USERNAME }}
          CSS_JFROG_PASSWORD: ${{ secrets.CSS_JFROG_PASSWORD }}
          DEFAULT_JFROG_USERNAME: ${{ secrets.DEFAULT_JFROG_USERNAME }}
          DEFAULT_JFROG_PASSWORD: ${{ secrets.DEFAULT_JFROG_PASSWORD }}

      - name: Print JFrog Credentials
        id: printvars
        run: |
          echo "JFROG_USERNAME: $JFROG_USERNAME"
          echo "JFROG_PASSWORD: $JFROG_PASSWORD"
          echo "JFROG_USERNAME=$JFROG_USERNAME" >> $GITHUB_OUTPUT
          echo "JFROG_PASSWORD=$JFROG_PASSWORD" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: example-job
    steps:
      - name: print
        run: echo "$JFROG_USERNAME $JFROG_PASSWORD"
        env:
          JFROG_USERNAME: ${{ needs.example-job.outputs.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ needs.example-job.outputs.JFROG_PASSWORD }}
          
